<h1>Welcome to the <span id="zf-name">Zend wf!</span></h1>
<table>
    <thead>
    <tr>
        <th>Email</th>
        <th>Comment</th>
        <th>Created</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->guestbooks as $guestbook): ?>
        <tr>
            <td><?php echo $guestbook->email ?></td>
            <td><?php echo $guestbook->comment ?></td>
            <td><?php echo $guestbook->created ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
